language: python
cache: pip
os:
- linux
python:
- '3.6'
install:
- pip install numpy scipy pandas
- pip install .
- pip install pytest==4.3
script: python -m pytest
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: alejoe91
  on:
    tags: true
  password:
    secure: jCoHWsWiD/PRDmPyZjTnVR8aVIsLZq9F/n+9kcNpvWv5RWACyKt+27DmT++SWwuVMqWovkBymZla1rq/V7+D1UzrhCZ+Eb/BpcJ0u7nLDmPUbaLeUxAwpwOxP3I9b5Xd4Jyoc9YY6FBDQJfz/kjmSznWDjK29pD3P8RiqKPRHlbUfA4AY0Lmlf4t0So8dUG12ilmMJC85Qh4smZaFFI4WZunUrMbn5lVSDuzZXxpZoHki2OINLBEKRp/fLPK2vb0TzZaR9i4dI8D9CdJbDb4M9I+LKUU8m4Da49Ch3K8JhIxlUiDcFNBxAk2M3OMKe+9ibnNfrr/UDPinjhCPi2SpTD11MbB53vwZZ0xi31KjwVbaApC7oruknHHPDD2I9zo1Y8r/MSfuhup3wPC6D7w/m+OtLtveCiBpW13I321Kt+GWGu6pn2y1ccF+dLzrgENeZ7qPgSE5EE2UVp25oHzott3KBGVFdKR3cRl6cz313lQiSStSUGV/eeIPkje4YxrrYvvPQVa+80Xu+sTDCpD0eA6my5vfNbweqadkqYpjYD4Oa1aufvZ0qUmfirMuzeWhTVA5F7t7fzAdc79KqLZKCorDqFj7mG85aIebvE4xfVpgswgChGeOp2g9Ep663VNb1d0cOnqcDCQv/BA9+jH/LohgQ6VJU6TpsZSQNyfnv0=
